# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# The docker image we want to run within.
executors:
  node_executor:
    docker:
      - image: circleci/node:12

# Created commands to save rewriting code.
commands:
  restore_npm_cache:
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
  save_npm_cache:
    steps:
      - save_cache:
          name: Cache npm dependencies
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
          paths:
            - node_modules

# A list of all the possible jobs to run.
jobs:
  # This job sets up the project and installs all the npm packages and saves them to cache.
  setup:
    executor:
      name: node_executor
    steps:
      - checkout
      - restore_npm_cache
      - run: npm install
      - save_npm_cache
  # This job runs all the unit tests within the project.
  test_unit:
    executor:
      name: node_executor
    steps:
      - checkout
      - restore_npm_cache
      - run: npm run test test/unit
  # This job runs all the integration tests within the project.
  # This requires generating and deploying to the test website first before
  # running the integration tests.
  # TODO: Test this job and then add to workflows.
  test_integration:
    executor:
      name: node_executor
    steps:
      - checkout
      - restore_npm_cache
      - run: npm run generate
      - run: ./node_modules/.bin/firebase deploy -P default --token "$FIREBASE_TOKEN"
      - run: cp .env.example .env
      - run: sed -i 's/BROWSERSTACK_USERNAME=/BROWSERSTACK_USERNAME=$BROWSERSTACK_USERNAME/g' .env
      - run: sed -i 's/BROWSERSTACK_AUTOMATE_KEY=/BROWSERSTACK_AUTOMATE_KEY=$BROWSERSTACK_AUTOMATE_KEY/g' .env
      - run: npm run test test/integration
  # This job deploys the project to the production website.
  deploy:
    executor:
      name: node_executor
    steps:
      - checkout
      - restore_npm_cache
      - run: npm run generate
      - run: ./node_modules/.bin/firebase deploy -P production --token "$FIREBASE_TOKEN"

# Workflows, the order to run a selection of jobs.
workflows:
  commit:
    jobs:
      - setup
      - test_unit:
          requires:
            - setup
      - deploy:
          requires:
            - test_unit
          filters:
            branches:
              only:
                - master
  nightly:
    triggers: # Triggers is a key to indicate a scheduled build
      - schedule: # 4 spaces needed underneath schedule.
          cron: "0 0 * * *" # Cron Syntax for nightly
          filters:
            branches:
              only:
                - master
    jobs:
      - setup
      - test_unit:
          requires:
            - setup
