# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# The docker image we want to run within.
executors:
  node_executor:
    docker:
      - image: circleci/node:12

# Created commands to save rewriting code.
commands:
  restore_npm_cache:
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
  save_npm_cache:
    steps:
      - save_cache:
          name: Cache npm dependencies
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
          paths:
            - node_modules

# A list of all the possible jobs to run.
jobs:
  setup_job:
    executor:
      name: node_executor
    steps:
      - checkout
      - restore_npm_cache
      - run: npm install
      - save_npm_cache
  test_job:
    executor:
      name: node_executor
    steps:
      - checkout
      - restore_npm_cache
      - run: npm run test

# Workflows, the order to run a selection of jobs.
workflows:
  run_tests:
    jobs:
      - setup_job
      - test_job
