# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# The docker image we want to run within.
executors:
  node_executor:
    docker:
      - image: circleci/node:12

# Created commands to save rewriting code.
commands:
  restore_npm_cache:
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
  save_npm_cache:
    steps:
      - save_cache:
          name: Cache npm dependencies
          key: npm-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
          paths:
            - node_modules

# A list of all the possible jobs to run.
jobs:
  setup:
    executor:
      name: node_executor
    steps:
      - checkout
      - restore_npm_cache
      - run: npm install
      - save_npm_cache
  test:
    executor:
      name: node_executor
    steps:
      - checkout
      - restore_npm_cache
      - run: npm run test
  deploy:
    executor:
      name: node_executor
    steps:
      - checkout
      - restore_npm_cache
      - run: npm run generate
      - run: firebase deploy -P production --token "$FIREBASE_TOKEN"

# Workflows, the order to run a selection of jobs.
workflows:
  commit:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
  nightly:
    triggers: # Triggers is a key to indicate a scheduled build
      - schedule: # 4 spaces needed underneath schedule.
          cron: "0 0 * * *" # Cron Syntax for nightly
          filters:
            branches:
              only:
                - master
    jobs:
      - setup
      - test:
          requires:
            - setup
