# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# The docker image we want to run within.
executors:
  node_executor:
    docker:
      - image: circleci/node:12

# A list of all the possible jobs to run.
jobs:
  setup:
    executor:
      name: node_executor
    steps:
      - checkout
      - run: npm install
  test:
    executor:
      name: node_executor
    steps:
      - checkout
      - run: npm run test

# Workflows, the order to run a selection of jobs.
workflows:
  commit:
    jobs:
      - setup
      - test
  nightly:
    triggers: # Triggers is a key to indicate a scheduled build
      - schedule: # 4 spaces needed underneath schedule.
          cron: "0 0 * * *" # Cron Syntax for nightly
          filters:
            branches:
              only:
                - master
    jobs:
      - setup
      - test
